### ISSUE TITLE
transparency

### ISSUE THREAD

**Issue by Kanyona** [Groupe-ElementR/cartography#13]
I could not find the option of adjust the transparency level on all colors! Is it possible to add the option transparency when you plot with colors (I did not find). 
regards
Byman

**Comment by rCarto** [comment]
You can use hexa colors in `cartography` functions (this format: "#923422"). On hexa colors you can add 2 digits at the end of the color string to indicate the level of transparency ("#99000050" will be a red color with 50% of transparency)
Also the `carto.pal` function has an option to set transparency.

**Comment by Kanyona** [comment]
Ok.. many thanks
