### ISSUE TITLE
Adapt to resize

### ISSUE THREAD

**Issue by RCura** [Groupe-ElementR/cartography#14]
I don't know how it can be done, but it can be : https://twitter.com/slowkow/status/696710285080600578

This would help with the always-happening issue of plot window size not being adapted.

**Comment by rCarto** [comment]
Err... I don't do ggplot ;-)

But you can have a look at the new getFigDim function. This function help to get output figure dimension based on a spatial object dimension ratio (works with raster and vector format)..
A short example:
```r
data("nuts2006")
spdf <- nuts0.spdf[nuts0.spdf$id=="IT",]
## PNG export
# get figure dimension
sizes <- getFigDim(spdf = spdf, width = 450, mar = c(0,0,1.2,0))
# export the map
png(filename = "Italy.png", width = sizes[1], height = sizes[2])
par(mar = c(0,0,1.2,0))
plot(spdf, col  = NA, border=NA, bg = "#A6CAE0")
plot(world.spdf, col  = "#E3DEBF", border=NA, add=TRUE)
plot(spdf, col  = "#D1914D", border="white", add=T)
layoutLayer(title = "Map of Italy")
dev.off()
```
The figure will fit the map dimension, with no extra margins. 
But, ok, the function is useless in the interactive session...
