### ISSUE TITLE
Could other symbols be used in propSymbolsChoroLayer() ?

### ISSUE THREAD

**Issue by sylvaticus** [Groupe-ElementR/cartography#18]
Hello, it would be nice to have symbols like triangleTop and triangleBottom (or circles) in propSymbolsChoroLayer().
In this way, printing two layers, one could use also the colour of the triangles  - and not just the size, as in propTrianglesLayer() - as the measure of a further dimension.
It would also make propTrianglesLayer() redundant.

A more general approach would be to print circles with two further parameters: the initial angle and the arc angle: in this way one could, using repeated calls to this method, compose a "cake" in each polygon where the size and/or the colour of each  slice would come from a different variable.

Cheers !

**Comment by rCarto** [comment]
Hello,
I think we'll consider the triangle (top and bottom) suggestion. The legend would have to be properly adapted, We'll see...
But i dont think we'll go for the pie symbols. Their semiologic power is largely discussed, and we're more on the "anti-pie" side of the controverse...
Cheers
