### ISSUE TITLE
Bertin's style points regular grid

### ISSUE THREAD

**Issue by ljegou** [Groupe-ElementR/cartography#19]
Hello, looking into the script generating the vignette map, i've found that it's possible to use the gridding functions to generate a regular-grid point map, Bertin-style.

Cf. my presentation here : http://www.uoh.fr/front/document/ee86e66d/cdbb/47df/ee86e66d-cdbb-47df-a13e-bf502c963b0a/UOHGEOprod/Module116/pages/s6/page2417.xml

I'm not a pro of R, but here is my little script, using the data from the package:

```R
library(cartography)
data(nuts2006)

# Plot basemaps
plot(nuts0.spdf, border = NA, col = NA, bg = "#A6CAE0")
plot(world.spdf, col  = "#E3DEBF80", border=NA, add=TRUE)
plot(nuts0.spdf, border = "white", col = "#E3DEBF", lwd= 1.1, add=T)

# Compute the grid and its base values
mygrid <- getGridLayer(spdf = nuts0.spdf,cellsize = 50000)
datagrid.df <- getGridData(mygrid, nuts0.df, "pop2008", dfid=NULL)

# Compute the number of points in the polygons
np<-as.data.frame(table(mygrid$df$id_geo)

# Compute the value for each point of the grid

# Load dplyr to cross join the tables
library(dplyr)

# Compute the join between the grid and the list of point numbers by polygons
a <- inner_join(np, mygrid$df, by = c("Var1" = "id_geo"))

# Compute the join with the datagrid
c <- inner_join(a, datagrid.df)

# Compute the join with the data source
d<-inner_join(nuts0.df, c, by = c("id" = "Var1"))

# Calculate the value for each point of the grid (var / nb pts).
d$pop2008grid = d$pop2008.x / d$Freq

# Draw the map
propSymbolsLayer(spdf = mygrid$spdf, df = d, spdfid = "id", dfid = "id_cell", legend.pos = "n", border = "white", var = "pop2008grid", k=0.0001, col="darkblue", add=TRUE)
```

Thanks for your work, it'll be very useful for my students :)

**Comment by rCarto** [comment]
Yes, we had that possibility in mind (the french part of [this map](https://camo.githubusercontent.com/3e7bfd5daed10c69f341a027dba56e188450ac76/687474703a2f2f7267656f6d617469632e6879706f7468657365732e6f72672f66696c65732f323031362f30322f636172746f6d69782e706e67), the [code](https://gist.github.com/rCarto/ef52aa4e96a7b628956fbf531143ae68)).
