### ISSUE TITLE
Add legend.nodata.col to typoLayer()

### ISSUE THREAD

**Issue by the-knife** [Groupe-ElementR/cartography#21]
Hello,

Would it be possible to add a _legend.nodata.col_ parameter to the typoLayer() function to be able to have another color than white?

Thank you.

Pierre-Yves

**Comment by rCarto** [comment]
Hello, 
I think I'll add this parameter in a week or two.

**Comment by RCura** [comment]
Would be also good (and usefull here) to have in choroLayer :smiley:

**Comment by rCarto** [comment]
Sure
