### ISSUE TITLE
Add size to LayoutLayer 

### ISSUE THREAD

**Issue by alfcrisci** [Groupe-ElementR/cartography#22]
Congrats for your work.
It is possible to add size for title and source in LayoutLayer ?

Thank you in advance.

**Comment by rCarto** [comment]
I think I will accept your PR in a week or two. I just have to run some quick tests before...

**Comment by alfcrisci** [comment]
Merci

**Comment by rCarto** [comment]
The current `layoutLayer` function plot the title (cex = 0.8) within a box of 1.2 inches in height. This fixed size is quite handy to defines margins of figures for example.
Adding a sizetitle argument is manageable but we would lose the title fixed size feature...
I'll think about this problem... 
For now, you can use the `mtext` function to place sources and even the classic `title` function to add a title.
