### ISSUE TITLE
nclass problem with chorolayer

### ISSUE THREAD

**Issue by MarionLeTexier** [Groupe-ElementR/cartography#27]
Hi, 
first thanks a lot for the great package! 
I've just got a problem when using choroLayer with nclass=6 and method="sd". 
Wouldn't get the number of classes I've asked for. Any idea why? 
Thanks a lot!

**Comment by RCura** [comment]
Cartography uses `classInt` package, which docs says  :
> The "sd" style chooses breaks based on `pretty` of the centred and scaled variables, and may have a number of classes different from n

**Comment by rCarto** [comment]
That's true, but we have added some extra methods to complement classint. You can access a method strictly based on mean ans sd through the "msd" method in the getBreaks function. With "msd" you can choose the class sizes in number of sd.
