### ISSUE TITLE
Rgui et getGridLayer : erreur

### ISSUE THREAD

**Issue by mgageo** [Groupe-ElementR/cartography#28]
Bonsoir,

Sous Windows 10, R version 3.3.2patched, dans l'environnement Rgui, j'ai une erreur
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘spChFIDs’ for signature ‘"SpatialPolygonsDataFrame", "integer"’
En environnement "Rscript.exe", je n'ai pas d'erreur.

La partie significative de mon script
  library(sp)
  library(rgdal)
  library(rgeos)
  library(cartography)
  varDir <- sprintf("%s/bvi35/CouchesVilaineAval", Drive);
  dsn <- sprintf("%s/Nord.shp", varDir)
  layer <- ogrListLayers(dsn)
  spdf <- readOGR(dsn, layer=layer, stringsAsFactors=FALSE)
  spdf <- spTransform(spdf, CRS("+init=epsg:2154"))
  grille <- getGridLayer(spdf=spdf,cellsize = 1000)

J'avais ce même comportement en R version 3.3.1.

Dans le mode Rgui, la commande "names()" fonctionne de manière différente, c'est peut-être une piste ?

Et merci pour votre package qui est super pratique !

**Comment by rCarto** [comment]
Thanks. There was a problem with numeric (and factor) ids. Update cartography on your computer: 
``` r
require(devtools)
devtools::install_github("Groupe-ElementR/cartography")
```
and it should be ok.

**Comment by mgageo** [comment]
Merci, cela corrige bien le problème que j'avais.
J'ai modifié getGridLayer pour avoir des mailles en projection plane alignées sur le carroyage. Par exemple, pour un pas de 1000 mètres, je voulais avoir les coordonnées des angles en multiple de 1000.
Je mets le code si cela peut servir à d'autres
`getGridLayer2 <- function(spdf, cellsize, spdfid = NULL) {
  print(sprintf("getGridLayer2() début"))
  if (!requireNamespace("rgeos", quietly = TRUE)) {
    stop("'rgeos' package needed for this function to work. Please install it.",
    call. = FALSE)
  }
  print(str(spdf@data))
  if (is.null(spdfid)){
    spdfid <- names(spdf@data)[1]
  }
  spdf@data <- spdf@data[spdfid]
  row.names(spdf@data)<-spdf@data[,spdfid]
  spdf <- spChFIDs(spdf, spdf@data[,spdfid])
  spdf@data$area <- rgeos::gArea(spdf, byid=TRUE)

  boundingBox <- bbox(spdf)
  rounder <- boundingBox %% cellsize
  boundingBox[,1] <- boundingBox[,1] - rounder[,1]
  roundermax <- cellsize - rounder[,2]
  boundingBox[,2] <- boundingBox[,2] + cellsize - rounder[,2]
  print(str(boundingBox))
  boxCoordX <- seq(from = boundingBox[1,1]-cellsize/2, to = boundingBox[1,2]+cellsize/2, by = cellsize)
  boxCoordY <- seq(from = boundingBox[2,1]-cellsize/2, to = boundingBox[2,2]+cellsize/2, by = cellsize)
  spatGrid <- expand.grid(boxCoordX, boxCoordY)
  spatGrid$id <- seq(1, nrow(spatGrid), 1)
  coordinates(spatGrid) <- 1:2 # promote to SpatialPointsDataFrame
  gridded(spatGrid) <- TRUE # promote to SpatialPixelsDataFrame
  spgrid <- methods::as(spatGrid, "SpatialPolygonsDataFrame") # promote to SpatialPolygonDataFrame

  proj4string(spgrid) <-proj4string(spdf)
  row.names(spgrid) <- as.character(spgrid$id)

  # On ne garde que ce qui touche le fond de carte initial
  over <- rgeos::gIntersects(spgrid, spdf, byid = TRUE)
  x <- colSums(over)
  spgrid <- spgrid[spgrid$id %in% names(x[x>0]),]

  mask <- rgeos::gBuffer(spdf, byid=FALSE, id=NULL, width=1.0, quadsegs=5, capStyle="ROUND",joinStyle="ROUND", mitreLimit=1.0)
  spgrid <- rgeos::gIntersection(spgrid, mask, byid=TRUE, id=as.character(spgrid@data$id), drop_lower_td=FALSE)
  data <- data.frame(id=sapply(methods::slot(spgrid, "polygons"), methods::slot, "ID"))
  row.names(data) <- data$id
  spgrid<-SpatialPolygonsDataFrame(spgrid, data)
  spgrid@data$cell_area <- rgeos::gArea(spgrid, byid=TRUE)
  proj4string(spgrid) <-proj4string(spdf)

  # On calcule la table de passage
  # intersection
  parts <- rgeos::gIntersection(spgrid, spdf, byid=TRUE,drop_lower_td=TRUE)
  data <- data.frame(id=sapply(methods::slot(parts, "polygons"), methods::slot, "ID"))
  tmp <- data.frame(do.call('rbind', (strsplit(as.character(data$id)," "))))
  data$id1 <- as.vector(tmp$X1)
  data$id2 <- as.vector(tmp$X2)
  row.names(data)<-data$id
  parts<-SpatialPolygonsDataFrame(parts, data)
  proj4string(parts) <-proj4string(spdf)

  # Part de surface intersectée
  parts@data$area_part <- rgeos::gArea(parts, byid=TRUE)
  parts@data <- data.frame(parts@data,  area_full=spdf@data[match(  parts@data$id2, spdf@data[,spdfid]),"area"])
  parts@data$area_pct <- (parts@data$area_part/parts@data$area_full)*100
  areas <- parts@data[,c("id1","id2","area_pct")]
  colnames(areas) <- c("id_cell","id_geo","area_pct")
  return(list(spdf = spgrid, df = areas))
}`

**Comment by rCarto** [comment]
merci
