### ISSUE TITLE
getGridLayer : une question, comment conserver des mailles entières

### ISSUE THREAD

**Issue by mgageo** [Groupe-ElementR/cartography#29]
Bonjour,

Je veux produire une grille "Lambert" avec des mailles entières.
En modifiant getGridSquare, j'arrive bien à ce que les mailles soient alignées sur le quadrillage Lambert.
`  boundingBox[,1] <- boundingBox[,1] - rounder[,1] - cellsize/2
    boundingBox[,2] <- boundingBox[,2] - rounder[,2] + cellsize + cellsize/2`
Par contre je ne trouve pas comment enlever l'intersection des mailles.

Je voudrais mettre un nom de maille du type E9999N9999, la partie numérique dépendant du coin en bas à gauche. Cela est-il possible ?

**Comment by rCarto** [comment]
Bonjour, 
Tous cela est bien sûr possible. Cependant votre demande dépasse un peu le cadre du package. 
Nous réfléchirons à l'addition de fonctions de création de grilles plus paramétrables, mais je ne suis pas sûr que nous allions dans ce sens...
